krimaApp/urls.py
from django.contrib import admin
from django.urls import path
from .import views as v

urlpatterns = [
    path('admin/', admin.site.urls),

    # Admin Urls
    path('',v.Index_Page),
    # Admin Dashboard Url
    path('dashboard',v.AdminDashboard),
   
    path('logout_user',v.Logout_user),
    # Admin Uploaded file Data View url
    path('view_file/<int:id>',v.Admin_file_view),
    # Delete File
    path('delete_file/<int:id>',v.Delete),
    # Push File To Qc
    path('push/<int:id>',v.Push_to_Qc),
    # Send Files History Url
    path('qc_file_record',v.Qc_history),
    # Editor received Url
    path('ed_file_record',v.Ed_record),
    # All user List
    path('all_user',v.All_user),
    # Download File
    path('Download/<int:id>',v.Download),
    # About-us url
    path('about_us',v.About),
    # Feature Page
    path('feature',v.Feature),

    # # delete user
    # path('d_user/<int:id>',v.Delete_user),


    # Qc User Profile Create Url
    path('make_qc',v.Make_Qc),
    # Qc User Login Url
    path('qc_login',v.QC_login), 
    # Otp Verification Url
    path('verify_otp',v.verify_otp),
    # QC Dashboard Url
    path('qc_home',v.QC_home),
    # QC Profile Show Url
    path('qc_view_file/<int:id>',v.QC_file_view),
    # Delete File
    path('del_qc/<int:id>',v.Delete_qc),
    # QC Apply Filter
    path('filter_srh/<int:id>',v.Qc_filter),
    # Qc Edit file Data
    path('qc_edit_data/<int:id>/<int:pid>',v.Qc_edit_date),
    # Qc AFter Filetr edit data
    path('qc_edit_filter_data/<int:id>/<int:pid>',v.Qc_filter_edit),
    # Qc Bulk-Edit Url
    path('data_srh/<int:id>',v.Bulk_Data_save),
    # Add Rows\Copy Data Full row Url
    path('Add_rows/<int:id>/<int:pid>',v.Add_rows),
    # Filter After Add rows Url
    path('filter_Add_rows/<int:id>/<int:pid>',v.filter_Add_rows),
    # Qc Delete Rows
    path('qc_delete_data/<int:id>/<int:pid>/',v.Delete_row),
    # File Send To Final Editor
    path('qc_push/<int:id>',v.Send_file),
    

     # Editor User Profile Create Url
    path('make_ed',v.Make_ed),
    # Editor Login url
    path('ed_login',v.ED_login),
    # Otp Verification Url
    path('verify_otp1',v.verify_otp1),
     # Editor Dashboard Url
    path('ed_home',v.ED_home),
    
    path('ed_view_file/<int:id>',v.Ed_file_view),
    # Editor Apply Filter
    path('ed_filter_srh/<int:id>',v.Ed_filter),
    # Editor Bulk-Edit Url
    path('ed_data_srh/<int:id>',v.Ed_Bulk_Data_save),
    # Editor Edit file Data
    path('ed_edit_data/<int:id>/<int:pid>',v.Ed_edit_date),
    # Editor AFter Filetr edit data
    path('ed_edit_filter_data/<int:id>/<int:pid>',v.Ed_filter_edit),
    # Final File Send To Admin For Download
    path('ed_push/<int:id>',v.Ed_Send_file),
    # Error/Doubts Url
    # path('message/<int:id>',v.Message),
]

krimaProject/urls.py
from django.contrib import admin
from django.urls import path,include
from krimaProject import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('krimaApp.urls'))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

krimaApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms

# Create your models here.
    
class My_Upload_file(models.Model):
    file=models.FileField()
    count=models.IntegerField(null=True)
    o_len=models.IntegerField(null=True)
    from_date=models.CharField(max_length=100,null=True)
    to_date=models.CharField(max_length=100,null=True)
    status=models.BooleanField(default=False)
    date=models.DateField(auto_now=True)
    def __str__(self):
        return self.file.name

    
class Qc_user(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)   
    def __str__(self):
        u=self.user.first_name+'-'+self.user.last_name
        return u
    
class my_Qc_data(models.Model):
    my_file=models.ForeignKey(My_Upload_file,on_delete=models.CASCADE)
    qc_file=models.FileField(upload_to='qc')
    from_date=models.CharField(max_length=100,null=True)
    to_date=models.CharField(max_length=100,null=True)
    user=models.ForeignKey(Qc_user,on_delete=models.CASCADE)
    start=models.IntegerField(default=0)
    date=models.DateField(auto_now=True)
    end=models.IntegerField()
    status=models.BooleanField(default=False)
    
    

class qc_Form(forms.ModelForm):
    class Meta:
        model=my_Qc_data
        fields=['user']



class ED_User(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)  
    def __str__(self):
        u=self.user.first_name+'-'+self.user.last_name
        return u

class Editor_push(models.Model):
    Editior=models.ForeignKey(ED_User,on_delete=models.CASCADE)
    qc_data=models.ForeignKey(my_Qc_data,on_delete=models.CASCADE)
    qc_user=models.ForeignKey(Qc_user,on_delete=models.CASCADE)
    rec_length=models.IntegerField()
    date=models.DateField(auto_now=True)
    sta=models.BooleanField(default=False)
    def __str__(self):
        return self.qc_data.qc_file.name
    

class pushForm(forms.ModelForm):
    class Meta:
        model=Editor_push
        fields=['Editior']


class Final_data_PM(models.Model):

    Editior=models.ForeignKey(ED_User,on_delete=models.CASCADE)
    Edited_file=models.ForeignKey(Editor_push,on_delete=models.CASCADE)
    date=models.DateField(auto_now=True)    
    status=models.BooleanField(default=False)

class Doubt(models.Model):
    file=models.ForeignKey(my_Qc_data,on_delete=models.CASCADE)
    user=models.ForeignKey(Qc_user,on_delete=models.CASCADE)
    Sr_no=models.CharField(max_length=100)
    msg=models.CharField(max_length=2000)

krimaApp/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages
from .models import *
from datetime import datetime
from krimaProject import settings
import json
import os
import smtplib
import random
import math
import copy
import pandas as pd
from django.urls import reverse
import openpyxl

# GMAIL-SMTP Cred.
SMTP_SERVER = 'smtp.gmail.com'
SMTP_PORT = 587
SMTP_USERNAME = 'amistreetecom0101@gmail.com'
SMTP_PASSWORD = 'xmxj ztoo dfvw bxtm'
sender_email = 'amistreetecom0101@gmail.com' 


# Index Page Views/logic Function
def Index_Page(request):
    if request.method=='POST':
        u=request.POST.get('un')
        p=request.POST.get('p')
        user=authenticate(User,username=u,password=p)  
        try: 
            if user.is_staff:
                request.session['uid']=user.id
                login(request,user)
                err='no' 
                messages.success(request,'Admin, you have logged in successfully.')
                return redirect('/dashboard')                
        except:
            # messages.error(request,'Something Went Wrong Please Try Againg')
            err='yes'                                
    return render(request,'admin_temps/index.html')

# Admin Home Page Function
def AdminDashboard(request):
    user=request.user
    file_data=My_Upload_file.objects.all() 
    qc=Qc_user.objects.all()
    data={'data':file_data,'qc':qc}
    try:
        list_date=[]
        date_obj=[]
        if request.method=='POST':
            u=My_Upload_file()
            fsh=request.FILES.get('file')
            u.file=fsh
            u.save()
        with open(f'{settings.BASE_DIR}//{fsh}','r') as f:
            f1=json.load(f)
        u.count=len(f1)
        u.o_len=len(f1)
        for i in f1:
            if i['Date'] != 'None' or i['Date'] != 'null':
               list_date.append((i['Date']))
        for i in list_date:
            date_str =i
            datetime_object = datetime.strptime(date_str,'%Y-%m-%d')
            date_object = datetime_object.date()
            date_obj.append(date_object)
        sorted_date=sorted(date_obj)
        u.from_date=sorted_date[0]
        u.to_date=sorted_date[-1]
        u.save()
        messages.success(request,'File Uploaded Successfully')
        return redirect('/dashboard')
    except:
        ...
        # messages.error(request,'Something Went Wrong Here Please Try Again Later')  
    return render(request,'admin_temps/admin_home.html',data)


# All User's Logout Function   
def Logout_user(request):
    logout(request)
    messages.success(request,'Your Profile Logout Successfully')
    return redirect('/')

# Admin File Delete Logic Function
def Delete(request,id):
    u=My_Upload_file.objects.get(id=id)
    file=u.file
    os.remove(f'{settings.BASE_DIR}//{file}')
    u.delete()
    return redirect('/dashboard')
# from django.shortcuts import get_object_or_404, redirect
# def Delete_user(request, id):
#     qc = get_object_or_404(Qc_user, id=id)
#     user = get_object_or_404(User, id=qc.user_id)
#     user.delete()
#     qc.delete()  # Delete qc after the user to avoid potential cascading issues
#     return redirect('/all_user')

# Admin File Data view Function
def Admin_file_view(request,id):
    list_date=[]
    date_obj=[]
    from_date=''
    to_date=''
    user=request.user
    
    try:    
        file_obj=My_Upload_file.objects.get(id=id)
        file_obj1=My_Upload_file.objects.filter(id=id)
        for i in file_obj1:
            file=i.file
        with open(f'{settings.BASE_DIR}//{file}','r') as f:
            f1=json.load(f)
        for i in f1:
            if i['Date'] != 'None' or i['Date'] != 'null':
               list_date.append((i['Date']))
        for i in list_date:
            date_str =i
            datetime_object = datetime.strptime(date_str,'%Y-%m-%d')
            date_object = datetime_object.date()
            date_obj.append(date_object)
        sorted_date=sorted(date_obj)
        from_date=sorted_date[0]
        to_date=sorted_date[-1] 
        data={'data':f1,'f':from_date,'t':to_date}      
    except:
        ...
    return render(request,'admin_temps/view_file.html',data)

# All user's List Show Functio
def All_user(request):
    
    user_types = {
        'QC': Qc_user.objects.all(),
        'Editor': ED_User.objects.all()
    }
    return render(request,'admin_temps/All_user.html',{'user_types':user_types})

# Admin File's no of records Alocate To QC function 
def Push_to_Qc(request,id):
    user=request.user
    file_obj1=My_Upload_file.objects.filter(id=id)
    for i in file_obj1:
        file=i.file
        date=i.date
    with open(f'{settings.BASE_DIR}//{file}','r') as f:
        f1=json.load(f)
    name=file.name
    length=len(f1)
    date=date    
    if request.method == 'POST':
        my_file = My_Upload_file.objects.get(id=id)
        file_name = request.POST.get('file_name')
        user_id = request.POST.get('user')
        end_index = int(request.POST.get('end'))
        print(end_index)
        # Load the original file
        file_path = f'{settings.BASE_DIR}/{my_file.file}'
        with open(file_path, 'r') as file:
            data = json.load(file)
        # Extract the desired chunk from the original file
        chunk = data[0:end_index]
        # print(chunk)
        # Create a new QC data instance
        qc = my_Qc_data()
        qc.qc_file = f'{file_name}.json'
        qc.my_file = my_file
        qc.end = end_index
        qc.user = Qc_user.objects.get(id=user_id)
        qc.save()
        # Save the chunk to a new file
        chunk_file_path = f'{settings.BASE_DIR}/{qc.qc_file}'
        if not os.path.exists(chunk_file_path):
            with open(chunk_file_path, 'w') as file:
                json.dump(chunk, file)
        else:
            print(f"File {chunk_file_path} already exists.")
        # Update the original file by removing the chunk
        data = data[end_index:]
        with open(file_path, 'w') as file:
            json.dump(data, file)
        # Extract dates from the updated original file
        dates = [datetime.strptime(item['Date'], '%Y-%m-%d').date() for item in data if item['Date'] not in ['None', 'null']]
        if dates:
            my_file.from_date = min(dates)
            my_file.to_date = max(dates)
        else:
            my_file.from_date = None
            my_file.to_date = None
        my_file.count = len(data)
        my_file.status=True
        my_file.save()
        # Extract dates from the chunk file
        with open(chunk_file_path, 'r') as file:
            chunk_data = json.load(file)
        dates = [datetime.strptime(item['Date'], '%Y-%m-%d').date() for item in chunk_data if item['Date'] not in ['None', 'null']]
        if dates:
            qc.from_date = min(dates)
            qc.to_date = max(dates)
        else:
            qc.from_date = None
            qc.to_date = None
        qc.save()
        with open(f'{settings.BASE_DIR}/{qc.qc_file}','r+') as f:
            f.seek(0)  # move file pointer to the beginning of the file
            f1 = json.load(f)
            for item in f1:
                item['Ok'] = 0
                item['method']=''
            f.seek(0)  # move file pointer to the beginning of the file again
            json.dump(f1, f)
            f.truncate()  # remove any remaining characters after the new JSON data
        messages.success(request,'File Send Successfully To Qc User')
        return redirect('/dashboard')
    else:
        form = qc_Form()
    return render(request,'admin_temps/push_form.html',{'form': form,'name':name,'length':length,'date':date})

# Admin Alocate file's Record History function
def Qc_history(request):
    data=my_Qc_data.objects.all()
    stats = []
    combined_list=[]
    for qc_data in data:
        file_path = f'{settings.BASE_DIR}//{qc_data.qc_file}'
        with open(file_path, 'r') as f:
            qc_file_data = json.load(f)

        counts = {
            'correct': 0,
            'error': 0,
            'rejected': 0,
            'unclassified': 0,
            'bulk':0
           
        }


        for item in qc_file_data:
            
            if item['Ok'] == '1':
                counts['correct'] += 1
            elif item['Ok'] == '0':
                counts['error'] += 1
            elif item['Ok'] == '2':
                counts['rejected'] += 1
            elif item['method'] == 'Bulk Edit':
                counts['bulk'] += 1
                
            else:
                counts['unclassified'] += 1


        stats.append(counts)
        combined_list = list(zip(data, stats))
        

    return render(request, 'admin_temps/qc_record.html', {
        'combined_list':combined_list
    })
   
# QC Profile Makeing By Admin Function
def Make_Qc(request):
    user=request.user
   
    err=''
   
    if request.method=='POST':
        f_n=request.POST.get('f_n')
        l_n=request.POST.get('l_n')  
        email=request.POST.get('email')
        p=request.POST.get('p')
        try:
            user=User.objects.create_user(first_name=f_n,last_name=l_n,email=email,username=email,password=p)
            Qc_user.objects.create(user=user)
            err='no'
            messages.success(request,'QC Profile Created Successfully')    
            return redirect('/dashboard')
        except:
            err='yes'     
    return render(request,'qc_temps/make_qc.html')

# QC User Login Function 
def QC_login(request):
    if request.method == 'POST':
        u = request.POST.get('email')
        p = request.POST.get('p')
        user = authenticate(User, username=u, password=p)
        if user is not None:
            request.session['uid'] = user.id
            receiver_email = u
            otp_length = 6
            otp = math.floor(random.random() * 10**(otp_length-1) + 10**(otp_length-1))

krimaApp/templates/admin_temps/All_user.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Report</title>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        /* Navbar styling */
        .navbar {
            background-color: #343a40;
            padding: 1rem;
        }

        .navbar-brand img {
            width: 230px;
            height: 45px;
        }

        .nav-link {
            color: #ffffff !important;
            font-weight: 500;
            margin-left: 15px;
        }

        .nav-link:hover {
            color: #c9cc00 !important;
        }

        .navbar-user {
            margin-left: auto;
            color: #ffffff;
            font-size: 1rem;
            font-weight: 600;
        }

        /* Page header styling */
        h1 {
            font-size: 1.8rem;
            font-weight: 700;
            color: #343a40;
            margin-top: 20px;
            text-align: center;
        }

        h2 {
            font-size: 1.4rem;
            font-weight: 600;
            color: #dc3545;
            margin-top: 30px;
            text-align: left;
        }

        /* Table styling */
        table {
            border-collapse: collapse;
            width: 100%;
            margin-top: 10px;
            background-color: #ffffff;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: center;
            font-size: 1rem;
        }

        th {
            background-color: #f8f9fa;
            color: #495057;
            font-weight: 700;
        }

        td {
            font-weight: 500;
        }

        tr:hover {
            background-color: #f1f1f1;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand" href="#">
                <img src="/static/image/logo.png" alt="Logo">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="/dashboard">Home</a>
                    </li>
                </ul>
                <div class="navbar-user">
                    <span>User - <strong>{{ user }}</strong></span>
                </div>
            </div>
        </div>
    </nav>

    <div class="container my-4">
        <h1>Here are Your Users</h1>

        {% for user_type, users in user_types.items %}
        <h2>{{ user_type }} Users</h2>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Username</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                    <td class="text-primary">{{ user.user.first_name }}</td>
                    <td class="text-primary">{{ user.user.last_name }}</td>
                    <td class="text-primary">{{ user.user.email }}</td>
                    <td class="text-primary">{{ user.user.username }}</td>
                    
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endfor %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
</body>

</html>

krimaApp/templates/admin_temps/about.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About-us</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <style>
            body{
                font-family: Verdana, Geneva, Tahoma, sans-serif;
            }
        </style>
</head>

<body>

    <div class="container">
        <!-- About 3 - Bootstrap Brain Component -->
        <section class="py-3">
            <div class="container ">
                <div class="row justify-content-md-center">
                    <div class="col-12 col-md-10 col-xxl-8">
                        <img class="img-fluid" loading="lazy" src="/static/image/logo.png" height="60px" width="300px"
                            alt="About 3">
                    </div>
                </div>
            </div>

            <div class="container overflow-hidden">
                <div class="row gy-2 gy-md-0 justify-content-xxl-center">
                    <div class="col-12 order-md-1 col-md-8 col-xxl-6">
                        <div class="text-center text-md-start">
                            <h2 class="display-3 fw-bold lh-1">Kasturirangan P</h2>
                            <p class="text-secondary">Founder & CEO of <b><i>Krima Solutions</i></b></p>
                            <hr class="w-25 mx-auto ms-md-0  text-secondary">
                            <h3 class="text-center" style="color: rgb(104, 102, 102);font-size: 28px;font-weight: 300;">
                                We Are Krima Solutions
                            </h3>
                            <h4 class="text-center" style="color: black;font-weight: 700;font-size: 28px;">We deliver
                                thought out solutions....through technology.</h4>
                            <p style="overflow-y: scroll;height: 270px;">Krima Solutions is a new economy firm that
                                believes in <mark
                                    style="color: rgb(233, 134, 6);background-color: transparent;">technology enabled
                                    services</mark> that
                                enhance end-customer experience of digital assets owned by corporations, digital
                                publishing firms, event firms and ecommerce companies. Krima provides entire <mark
                                    style="color: rgb(233, 134, 6);background-color: transparent;">digital
                                    lifecycle services</mark> for building and maintaining digital assets. We plan for,
                                design and
                                conceptualise digital assets. Developing <mark
                                    style="color: rgb(233, 134, 6);background-color: transparent;">customer-focused
                                    UX/UI</mark> and providing
                                <mark style="color: rgb(233, 134, 6);background-color: transparent;">researched
                                    content</mark> and its ongoing maintenance is our core expertise. We provide
                                on-going and
                                routine <mark style="color: rgb(233, 134, 6);background-color: transparent;">forensics
                                    on online user behaviour</mark> & preferences and help clients tweak their
                                digital design and content strategy for more effective results.

                                We have been able to solve several challenges and pain-staking problems to generate
                                meaningful and relevant data from unstructured, disparate medium of information onto a
                                structured database/platform. Our clients can get access to <marl
                                    style="color: rgb(233, 134, 6);background-color: transparent;">processed information
                                    on a
                                    near-live basis </marl> with speed and accuracy. <marl
                                    style="color: rgb(233, 134, 6);background-color: transparent;">AI created machine
                                    learning algorithms</marl>
                                constantly improve themselves.

                                SMART BASICS is what we follow. No big frills of huge physical infrastructure, but one
                                that is functional and top class in effectiveness. A huge focus on working with
                                best-in-class professionals we believe in <marl
                                    style="color: rgb(233, 134, 6);background-color: transparent;font-size: 16px;">
                                    "SMART BASICS"</marl>. Clients fully leverage their
                                access to our skilled resources be it automation experts or researchers and analysts.
                                Our deliverables focus purely on three simple things: correctness, completeness and
                                timeliness. This enables our objective of enabling our clients to enhance value through
                                cost and beyond.

                                Innovation, problem solving ability, proactivity from Krima Solutions will help you
                                enhance your brands and the digital assets. We help you with <marl
                                    style="color: rgb(233, 134, 6);background-color: transparent;">technology that is
                                    cutting-edge;</marl> one that is effective, efficient, result oriented and yes,
                                definitely
                                disruptive.
                            </p>

                        </div>
                    </div>
                    <div class="col-12 order-md-0 col-md-4 col-xxl-4">
                        <div class="text-center text-md-start me-md-3 me-xl-5">
                            <p class="mb-4">
                                <span class="d-block display-6 lh-1">Startup</span>
                                <span class="fs-4 text-secondary">Growing Startup</span>
                            </p>
                            <div class="d-grid">

                                <a href="/" class="btn btn-outline-primary btn-lg">Home</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>




</body>

</html>

krimaApp/templates/admin_temps/push_form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Record Assgin Form</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        body {
            background-color: #f5f5f5;
            font-family: Verdana, Geneva, Tahoma, sans-serif;
        }

        .container {
            max-width: 1100px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border: 1px solid #ddd;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-radius: 20px;
        }

        .form-label {
            font-weight: bold;
        }

        .form-control {
            height: 40px;
            padding: 10px;
            font-size: 16px;
            border-radius: 10px;
        }

        .btn-primary {
            width: 100%;
            font-size: 18px;
            padding: 10px;
            border-radius: 20px;
        }
        .btn-outline-success {
            width: 100%;
            font-size: 18px;
            padding: 10px;
        }
    </style>
</head>

<body>
    <div>
        <h4><a href="/dashboard" class="btn btn-outline-success">Back To Home</a></h4>
    </div>
    <div class="d-flex align-items-center">
        <img src="/static/image/logo.png" alt="" style="width: 310px; height: 50px; ">
        
            <p class="text-dark fs-5 nav-link active " style="margin-left: 640px;"><strong class="text-dark">User - </strong> <b>{{user}}</b></p>

       
        
    </div>
    <h2 class="text-center p-2">Record Assign Form</h2>
    <div class="container d-flex" style="width: 100%;">
        <div class="container shadow-lg bg-white rounded" style="width: 100%;">
            <form class="row g-3" method="post">
                {% csrf_token %}
                <div class="col-12 form-label">
    
                    {{ form.as_table }}
                </div>
                <div class="col-12">
                    <label for="id_user" class="form-label">Enter Name For Creating File:</label>
                    <input type="text" name="file_name" id="" placeholder="qc_12" required class="form-control">
                </div>
                <div class="col-12">
                    <label for="id_user" class="form-label">Number Of Records:</label>
                    <input type="number" name="end" id="" required placeholder="End Record Number" class="form-control">
                </div>
                <div class="col-12 text-center">
                    <button type="submit" class="btn btn-primary">Assign</button>
                </div>
            </form>
        </div>
        <div class="container">
            <table class="table table-hover">
                <h3 class="text-center my-4 mx-2 py-2 px-2">File Stats</h3>
                <tr>
                    <th class="text-dark  text-center">File Name</th>
                    <th class="text-dark  text-center">Records Length</th>
                    <th class="text-dark  text-center">Upload Date</th>
                </tr>
                <tr>
                    <td class="text-center">
                        <abbr title=" {{name}}" style="text-decoration: none;" >{{name|truncatechars:20}}</abbr></td>
                    <td class="text-center">{{length}}</td>
                    <td class="text-center">{{date}}</td>
                </tr>
            </table>

        </div>

    </div>
</body>

</html>